import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import SportyFyProvider from "@/provider/SportyfyProvider";

const raleway = Raleway({
  variable: "--font-geist-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable}  antialiased`}
      >
        
          <SportyFyProvider>{children}</SportyFyProvider>
    
      </body>
    </html>
  );
}
